from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('product_add/', views.shopkeeper_product_add, name='product_add'),
    path('product_multiple_add/', views.shopkeeper_multiple_product_add, name='product_multiple_add'),
    path('product_all/', views.shopkeeper_all_products, name='product_all'),
    path('product_update/<int:pk>/', views.shopkeeper_product_update, name='product_update'),
    path('product_delete/<int:pk>/', views.shopkeeper_product_delete, name='product_delete'),
    path('product_view/<int:pk>/', views.product_view, name='product_view'),
    path('add_address/', views.add_address, name='add_address'),
    path('edit_address/<int:pk>', views.edit_address, name='edit_address'),
    path('manage_address/', views.manage_address, name='manage_address'),
    path('account_setting/', views.account_settings, name='account_setting'),
    path('create_tag/', views.shopkeeper_create_tag, name='create_tag'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('process_order/', views.process_order, name='process_order'),
    path('orders/', views.user_orders, name='orders'),
    path('view_invoice/<int:pk>/', views.view_invoice, name='view_invoice'),
    # path('get_invoice/<int:pk>/', views.download_and_view_invoice, name='get_invoice'),
    path('categories/<str:tag>/', views.categories, name='categories'),
    # path('search/', views.search, name='search'),
    path('search2', views.search2, name='search2'),
    path('temp/', views.temp, name='temp'),
    path('download_invoice/<int:pk>/', views.download_invoice, name="download_invoice"),
    path('shop_orders/', views.shop_orders, name='shop_orders'),
    path('users_list/', views.users_list, name='users_list'),
    path('create_coupon/<str:user_name>/', views.create_coupon, name='create_coupon'),
    path('get_coupon/<str:user_name>/', views.get_coupon, name='get_coupon'),
    path('apply_coupon/', views.apply_coupon, name='apply_coupon'),
]
