# Generated by Django 2.2.12 on 2022-04-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0015_auto_20220413_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='address',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
