# Generated by Django 2.2.12 on 2022-04-20 09:27

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220419_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('coupon_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('allowed_above', models.PositiveIntegerField(help_text='coupon is allowed above the price of')),
                ('start_on', models.DateTimeField(default=datetime.datetime(2022, 4, 20, 9, 27, 49, 737687, tzinfo=utc), help_text='coupon start date')),
                ('expire_on', models.DateTimeField(help_text='coupon end date')),
                ('discount', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='please enter discount percentage %', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('shopkeeper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Shopkeeper')),
            ],
        ),
    ]
