# Generated by Django 2.2.12 on 2022-04-20 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='coupon start date'),
        ),
    ]
