# Generated by Django 2.2.12 on 2022-04-21 05:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20220420_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='shopkeeper',
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_for',
            field=models.CharField(blank=True, help_text='coupon for', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='creator_name',
            field=models.ForeignKey(blank=True, help_text='coupon creator', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Shopkeeper'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='coupon text', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_name',
            field=models.CharField(blank=True, help_text='coupon_name', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='please enter discount percentage %', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
