# Generated by Django 2.2.12 on 2022-04-21 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20220421_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_on',
            field=models.DateField(help_text='coupon end date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_on',
            field=models.DateField(default=django.utils.timezone.now, help_text='coupon start date'),
        ),
    ]
