# Generated by Django 2.2.12 on 2022-04-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220421_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_on',
            field=models.DateField(help_text='coupon start date'),
        ),
    ]
