# Generated by Django 2.2.12 on 2022-04-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20220421_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_on',
            field=models.DateField(help_text='coupon end date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_on',
            field=models.DateField(help_text='coupon start date'),
        ),
    ]
