# Generated by Django 2.2.12 on 2022-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20220421_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_name',
            field=models.CharField(blank=True, help_text='coupon_name', max_length=50, null=True),
        ),
    ]
