# Generated by Django 2.2.12 on 2022-04-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20220421_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
